import os
from fpdf import FPDF
from datetime import datetime
from cost import format_currency
from carbon import format_carbon

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 20)
        self.cell(0, 10, 'EcoMind AI', 0, 1, 'C')
        self.set_font('Helvetica', 'I', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'Sustainability Intelligence Report', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by EcoMind AI', 0, 0, 'C')

def generate_pdf_report(data):
    """Generates a beautiful PDF report for a prompt optimization."""
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Metadata
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 6, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.cell(0, 6, f"Optimization Mode: {data['optimization_mode']}", 0, 1)
    pdf.cell(0, 6, f"Efficiency Score: {data['efficiency_score']}/100", 0, 1)
    pdf.ln(10)
    
    # Original Prompt
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'Original Prompt', 0, 1)
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 6, data['original_prompt'])
    pdf.ln(5)
    
    # Optimized Prompt
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(0, 100, 0)  # Greenish for optimized
    pdf.cell(0, 10, 'Optimized Prompt', 0, 1)
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 6, data['optimized_prompt'])
    pdf.ln(10)
    
    # Metrics Table
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'Intelligence Metrics', 0, 1)
    
    # Draw table
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(50, 10, 'Metric', 1)
    pdf.cell(45, 10, 'Before', 1)
    pdf.cell(45, 10, 'After', 1)
    pdf.cell(50, 10, 'Savings', 1)
    pdf.ln()
    
    pdf.set_font('Helvetica', '', 11)
    
    # Tokens
    pdf.cell(50, 10, 'Tokens', 1)
    pdf.cell(45, 10, str(data['original_tokens']), 1)
    pdf.cell(45, 10, str(data['optimized_tokens']), 1)
    pdf.set_text_color(0, 100, 0)
    pdf.cell(50, 10, str(data['tokens_saved']), 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln()
    
    # Cost (USD)
    pdf.cell(50, 10, 'Cost (USD)', 1)
    pdf.cell(45, 10, format_currency(data['original_cost'], "USD"), 1)
    pdf.cell(45, 10, format_currency(data['optimized_cost'], "USD"), 1)
    pdf.set_text_color(0, 100, 0)
    pdf.cell(50, 10, format_currency(data['cost_saved'], "USD"), 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln()
    
    # Carbon
    pdf.cell(50, 10, 'Carbon Footprint', 1)
    pdf.cell(45, 10, format_carbon(data['original_carbon']), 1)
    pdf.cell(45, 10, format_carbon(data['optimized_carbon']), 1)
    pdf.set_text_color(0, 100, 0)
    pdf.cell(50, 10, format_carbon(data['carbon_saved']), 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    
    # Output file
    output_filename = f"ecomind_report_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    output_path = os.path.join(os.getcwd(), output_filename)
    pdf.output(output_path)
    return output_path
